# Generated by Django 4.2.4 on 2024-04-22 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=8, unique=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='authentication_key',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user_library',
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IN_OUT', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_quantity', models.IntegerField()),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_files.masterinventory')),
            ],
        ),
    ]
