# Generated by Django 4.2.4 on 2024-04-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0002_masterinventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='IN_OUT',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10),
        ),
    ]
