# Generated by Django 4.2.4 on 2024-04-27 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0003_alter_inventorytransaction_in_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterinventory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
