# Generated by Django 4.2.4 on 2024-05-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0004_inventorytransaction_date_masterinventory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='start_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='IN_OUT',
            field=models.CharField(blank=True, choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10, null=True),
        ),
    ]
