# Generated by Django 4.2.4 on 2024-05-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0005_inventorytransaction_start_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinventory',
            name='item_class',
            field=models.CharField(choices=[('WP', 'Wp'), ('Other', 'Other')], default='WP', max_length=8),
        ),
    ]
