# Generated by Django 4.2.4 on 2024-05-16 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0006_masterinventory_item_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinventory',
            name='non_material',
            field=models.CharField(choices=[('N', 'n'), ('', '')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='masterinventory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 23, 53, 7, 16887, tzinfo=datetime.timezone.utc)),
        ),
    ]
